# Generated by Django 2.2.7 on 2020-01-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='acronym',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
