# Generated by Django 2.2.7 on 2020-01-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
