# Generated by Django 2.2.7 on 2020-01-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('block', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Floor')),
            ],
        ),
    ]
