# Generated by Django 2.2.7 on 2020-01-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Block'),
        ),
    ]
