# Generated by Django 2.2.7 on 2020-01-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200129_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=200)),
                ('ebm_receipt_create_on', models.DateField()),
                ('sub_total', models.IntegerField(default=0)),
                ('vat', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tenant')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
