# Generated by Django 2.2.7 on 2020-01-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200129_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='vat',
            new_name='tax_amount',
        ),
        migrations.AddField(
            model_name='billing',
            name='tax_rate',
            field=models.IntegerField(default=0),
        ),
    ]
