# Generated by Django 2.2.7 on 2020-01-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200130_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Building'),
        ),
    ]
