# Generated by Django 2.2.7 on 2020-02-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200130_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
