# Generated by Django 2.2.7 on 2020-11-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200205_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contract',
            field=models.FileField(default=None, upload_to='contracts/<django.db.models.fields.TextField>'),
        ),
        migrations.AlterField(
            model_name='building',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
