# Generated by Django 2.2.7 on 2020-11-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201123_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='contract',
        ),
    ]
