# Generated by Django 2.2.7 on 2020-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_tenant_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contract',
            field=models.FileField(default=1, upload_to='contracts/<django.db.models.fields.TextField>'),
            preserve_default=False,
        ),
    ]
