# Generated by Django 2.2.7 on 2020-11-27 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20201123_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='invoice_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
