# Generated by Django 2.2.7 on 2020-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20201127_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='invoice_no',
            field=models.TextField(default=0),
        ),
    ]
