# Generated by Django 2.2.7 on 2020-11-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20201127_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='acronym',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
